### ISSUE TITLE
Changing font-weight of the username and login button text

### ISSUE THREAD

**Issue by musjj** [Xubuntu/lightdm-gtk-greeter#147]
How do you change the font weight of the username and login button?

I tried using the following css:

```css
#login_window .entry {
  font-weight: 900;
}
```

But I don't see any changes.
